name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Web Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Extract branch name
        id: extract_branch_name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Deploy
        run: |
          BRANCH_FOLDER=$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/task\///g' | sed 's/_/-/g')
          aws s3 sync dist/ s3://webpreviewtest/$BRANCH_FOLDER --delete
